### ISSUE TITLE
[Bug] cursed vehicle variants on cullinton sandbox

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#198]
### Describe the bug

very weird color scheme on vehicle, this is extremely obvious on the green saloon found in the camp site, where entire vehicle feels like a green filter is layed upon it
which infact is probably wut you done to it:
![image](https://user-images.githubusercontent.com/81009804/162364301-6ed47e4b-99b1-4b9c-a838-22e89acbe275.png)
it all make sense when I saw the dual steering wheels, with one having the original color at the correct side, and the other one at the wrong side, or mirrored, and is the weird color
you remember voxbox are mirrored right, i even suggested a fix mirror properties for voxboxes, yeah thats the biggest giveaway here...
so did you guys just add a voxbox inside the same body, with the same model, removed the r and bump the g real high?
???????
the lights are all broken, even, did you not even copied the lights etc into the new voxbox?
and like with the original vox shape still in the body?
like, if you need more time, just... take your time, dont rush it, please?
oh wait you already announce that it will became official branch at 21st now
oh great

it also happened on the pickups near the campfire, tho less obvious then the green filtered saloon

### Steps to reproduce the behavior

1. Go to cullinton
2. go to campsite
3. feels weird
4. feels more weird
5. suffers
6. suffers so much that one finds needs to make a issue in github

### Expected behavior

no suffer

### Environment

- Teardown Version: 0.9.6
- OS: Windows 10
- GPU:
- Graphics driver version:
- CPU:

### Additional context

please

**Comment by tuxedolabs** [comment]
Should have been fixed in 1.0

**Comment by Please-Pick-a-Name** [comment]
> Should have been fixed in 1.0

the green saloon is however not fixed :)
![image](https://user-images.githubusercontent.com/81009804/173063029-76a0b205-afcb-4b47-a16d-b71e6b5498b3.png)
