### ISSUE TITLE
[Bug] Spawned scripts break on quickload

### ISSUE THREAD

**Issue by Thomasims** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#427]
### Describe the bug

Scripts instances created with the `Spawn` function that use a `MOD/` path (and possibly other special roots) don't correctly reload on quickload, the game throws a `Script not found` error in the console showing the script file path without the `MOD/` part.

### Steps to reproduce the behavior

1. Make a new script in a mod
2. Call `Spawn('<script file="MOD/script.lua"/>')` in the mod's main.lua
3. Quicksave and Quickload

### Expected behavior

The spawned script should resume at quickload like other scripts.

### Environment

- Teardown Version: 1.5.0
- OS: n/a
- GPU: n/a
- Graphics driver version: n/a
- CPU: n/a

**Comment by FlorentP42** [comment]
Do you think this could be related to the issue I experienced in #288 ?

**Comment by Thomasims** [comment]
> Do you think this could be related to the issue I experienced in #288 ?

No this was introduced with 1.5, there was a change made between experimental 1.5.0 patch 2 and release 1.5.1 (the error message changed) but it didn't fix the issue itself.

**Comment by Please-Pick-a-Name** [comment]
this seems to be mostly fixed, but need to deal with a specific odd thing that happenes after quickload, keep this open ig?

**Comment by YuLun-bili** [comment]
what is that odd thing?

> this seems to be mostly fixed, but need to deal with a specific odd thing that happenes after quickload, keep this open ig?

**Comment by Thomasims** [comment]
According to the devs this other issue was fixed in the latest experimental, I've not seen the issue firsthand so I'm closing this one on faith.

**Comment by EliRickard** [comment]
Hi All,

Feels like waking the dead here; sorry about that.

Appears this is still an issue with screen scripts. 

https://discord.com/channels/760105076755922996/768940642767208468/1345350366849531925

**Comment by UwQ-Official** [comment]
Can somebody re-open this issue as it looks like it's still valid

**Comment by Thomasims** [comment]
It's a rather different issue and this one is very old. #678 should be used although I agree with your comment there that the formatting on it is lacking.
